(setenv "HOME" "d:/emacs23")
(setenv "PATH" "d:/emacs23")
(setq default-directory "~/")
(load-file "~/zeconf/_eload")
(load-file "~/zeconf/_ebase")
(load-file "~/zeconf/_elang")
(load-file "~/zeconf/_eext")
(load-file "~/zeconf/_einc")
